using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using HtmlAgilityPackHelperLib;

namespace HtmlAgilityPackConsoleTest
{
    class Program
    {
        static void Main(string[] args)
        {
            #region aa
            StringBuilder sb = new StringBuilder();
            sb.Append("<!DOCTYPE html>");
            sb.Append("<html>");
            sb.Append("  <head prefix=\"og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# githubog: http://ogp.me/ns/fb/githubog#\">");
            sb.Append("    <meta charset='utf-8'>");
            sb.Append("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">");
            sb.Append("        <title>DeanZhouLin/HtmlAgilityPackCore</title>");
            sb.Append("    <link rel=\"search\" type=\"application/opensearchdescription+xml\" href=\"/opensearch.xml\" title=\"GitHub\" />");
            sb.Append("    <link rel=\"fluid-icon\" href=\"https://github.com/fluidicon.png\" title=\"GitHub\" />");
            sb.Append("    <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"/apple-touch-icon-114.png\" />");
            sb.Append("    <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"/apple-touch-icon-114.png\" />");
            sb.Append("    <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"/apple-touch-icon-144.png\" />");
            sb.Append("    <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"/apple-touch-icon-144.png\" />");
            sb.Append("    <link rel=\"logo\" type=\"image/svg\" href=\"https://github-media-downloads.s3.amazonaws.com/github-logo.svg\" />");
            sb.Append("    <meta property=\"og:image\" content=\"https://github.global.ssl.fastly.net/images/modules/logos_page/Octocat.png\">");
            sb.Append("    <meta name=\"hostname\" content=\"github-fe136-cp1-prd.iad.github.net\">");
            sb.Append("    <meta name=\"ruby\" content=\"ruby 1.9.3p194-tcs-github-tcmalloc (a846054d10) [x86_64-linux]\">");
            sb.Append("    <link rel=\"assets\" href=\"https://github.global.ssl.fastly.net/\">");
            sb.Append("    <link rel=\"conduit-xhr\" href=\"https://ghconduit.com:25035/\">");
            sb.Append("    <link rel=\"xhr-socket\" href=\"/_sockets\" />");
            sb.Append("    ");
            sb.Append("");
            sb.Append("");
            sb.Append("    <meta name=\"msapplication-TileImage\" content=\"/windows-tile.png\" />");
            sb.Append("    <meta name=\"msapplication-TileColor\" content=\"#ffffff\" />");
            sb.Append("    <meta name=\"selected-link\" value=\"repo_source\" data-pjax-transient />");
            sb.Append("    <meta content=\"collector.githubapp.com\" name=\"octolytics-host\" /><meta content=\"collector-cdn.github.com\" name=\"octolytics-script-host\" /><meta content=\"github\" name=\"octolytics-app-id\" /><meta content=\"74E40912:6F7C:75A5607:52CBA8BE\" name=\"octolytics-dimension-request_id\" /><meta content=\"5369038\" name=\"octolytics-actor-id\" /><meta content=\"DeanZhouLin\" name=\"octolytics-actor-login\" /><meta content=\"c9866ee0f137b48e0e32c6e85894e52d284c27a4a61e0f0d2c7331d14b63b50d\" name=\"octolytics-actor-hash\" />");
            sb.Append("    ");
            sb.Append("");
            sb.Append("    ");
            sb.Append("    ");
            sb.Append("    <link rel=\"icon\" type=\"image/x-icon\" href=\"/favicon.ico\" />");
            sb.Append("");
            sb.Append("    <meta content=\"authenticity_token\" name=\"csrf-param\" />");
            sb.Append("<meta content=\"GrFK1lxGTvXROnJB5Cw0b0LKIZMzeRGBUou9uNKmMYQ=\" name=\"csrf-token\" />");
            sb.Append("");
            sb.Append("    <link href=\"https://github.global.ssl.fastly.net/assets/github-4dd04ccaf246f824504ba07e20a70fbaf01e667e.css\" media=\"all\" rel=\"stylesheet\" type=\"text/css\" />");
            sb.Append("    <link href=\"https://github.global.ssl.fastly.net/assets/github2-e528a323feb29c53d05a1de6b96c8a2c138a6983.css\" media=\"all\" rel=\"stylesheet\" type=\"text/css\" />");
            sb.Append("    ");
            sb.Append("");
            sb.Append("    ");
            sb.Append("");
            sb.Append("      <script src=\"https://github.global.ssl.fastly.net/assets/frameworks-29a3fb0547e33bd8d4530bbad9bae3ef00d83293.js\" type=\"text/javascript\"></script>");
            sb.Append("      <script src=\"https://github.global.ssl.fastly.net/assets/github-4ac46f893910c3da1bdbe9b20092fe75867245d8.js\" type=\"text/javascript\"></script>");
            sb.Append("      ");
            sb.Append("      <meta http-equiv=\"x-pjax-version\" content=\"4a0380e154dc4b4493854b6fa2601ee0\">");
            sb.Append("");
            sb.Append("        <meta property=\"og:title\" content=\"HtmlAgilityPackCore\"/>");
            sb.Append("  <meta property=\"og:type\" content=\"githubog:gitrepository\"/>");
            sb.Append("  <meta property=\"og:url\" content=\"https://github.com/DeanZhouLin/HtmlAgilityPackCore\"/>");
            sb.Append("  <meta property=\"og:image\" content=\"https://github.global.ssl.fastly.net/images/gravatars/gravatar-user-420.png\"/>");
            sb.Append("  <meta property=\"og:site_name\" content=\"GitHub\"/>");
            sb.Append("  <meta property=\"og:description\" content=\"HtmlAgilityPackCore - HtmlAgilityPack的使用 封装基类\"/>");
            sb.Append("");
            sb.Append("  <meta name=\"description\" content=\"HtmlAgilityPackCore - HtmlAgilityPack的使用 封装基类\" />");
            sb.Append("");
            sb.Append("  <meta content=\"5369038\" name=\"octolytics-dimension-user_id\" /><meta content=\"DeanZhouLin\" name=\"octolytics-dimension-user_login\" /><meta content=\"15697538\" name=\"octolytics-dimension-repository_id\" /><meta content=\"DeanZhouLin/HtmlAgilityPackCore\" name=\"octolytics-dimension-repository_nwo\" /><meta content=\"true\" name=\"octolytics-dimension-repository_public\" /><meta content=\"false\" name=\"octolytics-dimension-repository_is_fork\" /><meta content=\"15697538\" name=\"octolytics-dimension-repository_network_root_id\" /><meta content=\"DeanZhouLin/HtmlAgilityPackCore\" name=\"octolytics-dimension-repository_network_root_nwo\" />");
            sb.Append("  <link href=\"https://github.com/DeanZhouLin/HtmlAgilityPackCore/commits/master.atom\" rel=\"alternate\" title=\"Recent Commits to HtmlAgilityPackCore:master\" type=\"application/atom+xml\" />");
            sb.Append("");
            sb.Append("  </head>");
            sb.Append("");
            sb.Append("");
            sb.Append("  <body class=\"logged_in  env-production windows vis-public\">");
            sb.Append("    <div class=\"wrapper\">");
            sb.Append("      ");
            sb.Append("      ");
            sb.Append("      ");
            sb.Append("      ");
            sb.Append("");
            sb.Append("");
            sb.Append("      <div class=\"header header-logged-in true\">");
            sb.Append("  <div class=\"container clearfix\">");
            sb.Append("");
            sb.Append("    <a class=\"header-logo-invertocat\" href=\"https://github.com/\">");
            sb.Append("  <span class=\"mega-octicon octicon-mark-github\"></span>");
            sb.Append("</a>");
            sb.Append("");
            sb.Append("    ");
            sb.Append("    <a href=\"/notifications\" class=\"notification-indicator tooltipped downwards\" data-gotokey=\"n\" title=\"You have no unread notifications\">");
            sb.Append("        <span class=\"mail-status all-read\"></span>");
            sb.Append("</a>");
            sb.Append("");
            sb.Append("      <div class=\"command-bar js-command-bar  in-repository\">");
            sb.Append("          <form accept-charset=\"UTF-8\" action=\"/search\" class=\"command-bar-form\" id=\"top_search_form\" method=\"get\">");
            sb.Append("");
            sb.Append("<input type=\"text\" data-hotkey=\"/ s\" name=\"q\" id=\"js-command-bar-field\" placeholder=\"Search or type a command\" tabindex=\"1\" autocapitalize=\"off\"");
            sb.Append("    ");
            sb.Append("    data-username=\"DeanZhouLin\"");
            sb.Append("      data-repo=\"DeanZhouLin/HtmlAgilityPackCore\"");
            sb.Append("      data-branch=\"master\"");
            sb.Append("      data-sha=\"fb9faf8fe86f55e401dcc20a50471dc1ce0904b5\"");
            sb.Append("  >");
            sb.Append("");
            sb.Append("    <input type=\"hidden\" name=\"nwo\" value=\"DeanZhouLin/HtmlAgilityPackCore\" />");
            sb.Append("");
            sb.Append("    <div class=\"select-menu js-menu-container js-select-menu search-context-select-menu\">");
            sb.Append("      <span class=\"minibutton select-menu-button js-menu-target\">");
            sb.Append("        <span class=\"js-select-button\">This repository</span>");
            sb.Append("      </span>");
            sb.Append("");
            sb.Append("      <div class=\"select-menu-modal-holder js-menu-content js-navigation-container\">");
            sb.Append("        <div class=\"select-menu-modal\">");
            sb.Append("");
            sb.Append("          <div class=\"select-menu-item js-navigation-item js-this-repository-navigation-item selected\">");
            sb.Append("            <span class=\"select-menu-item-icon octicon octicon-check\"></span>");
            sb.Append("            <input type=\"radio\" class=\"js-search-this-repository\" name=\"search_target\" value=\"repository\" checked=\"checked\" />");
            sb.Append("            <div class=\"select-menu-item-text js-select-button-text\">This repository</div>");
            sb.Append("          </div> <!-- /.select-menu-item -->");
            sb.Append("");
            sb.Append("          <div class=\"select-menu-item js-navigation-item js-all-repositories-navigation-item\">");
            sb.Append("            <span class=\"select-menu-item-icon octicon octicon-check\"></span>");
            sb.Append("            <input type=\"radio\" name=\"search_target\" value=\"global\" />");
            sb.Append("            <div class=\"select-menu-item-text js-select-button-text\">All repositories</div>");
            sb.Append("          </div> <!-- /.select-menu-item -->");
            sb.Append("");
            sb.Append("        </div>");
            sb.Append("      </div>");
            sb.Append("    </div>");
            sb.Append("");
            sb.Append("  <span class=\"octicon help tooltipped downwards\" title=\"Show command bar help\">");
            sb.Append("    <span class=\"octicon octicon-question\"></span>");
            sb.Append("  </span>");
            sb.Append("");
            sb.Append("");
            sb.Append("  <input type=\"hidden\" name=\"ref\" value=\"cmdform\">");
            sb.Append("");
            sb.Append("</form>");
            sb.Append("        <ul class=\"top-nav\">");
            sb.Append("          <li class=\"explore\"><a href=\"/explore\">Explore</a></li>");
            sb.Append("            <li><a href=\"https://gist.github.com\">Gist</a></li>");
            sb.Append("            <li><a href=\"/blog\">Blog</a></li>");
            sb.Append("          <li><a href=\"https://help.github.com\">Help</a></li>");
            sb.Append("        </ul>");
            sb.Append("      </div>");
            sb.Append("");
            sb.Append("    ");
            sb.Append("");
            sb.Append("");
            sb.Append("  <ul id=\"user-links\">");
            sb.Append("    <li>");
            sb.Append("      <a href=\"/DeanZhouLin\" class=\"name\">");
            sb.Append("        <img height=\"20\" src=\"https://1.gravatar.com/avatar/50d9216b6f47a2896ec49d14c92d408d?d=https%3A%2F%2Fidenticons.github.com%2F8fb1678b4db4d9b279f8b0bf431c496b.png&amp;r=x&amp;s=140\" width=\"20\" /> DeanZhouLin");
            sb.Append("      </a>");
            sb.Append("    </li>");
            sb.Append("");
            sb.Append("      <li>");
            sb.Append("        <a href=\"/new\" id=\"new_repo\" class=\"tooltipped downwards\" title=\"Create a new repo\" aria-label=\"Create a new repo\">");
            sb.Append("          <span class=\"octicon octicon-repo-create\"></span>");
            sb.Append("        </a>");
            sb.Append("      </li>");
            sb.Append("");
            sb.Append("      <li>");
            sb.Append("        <a href=\"/settings/profile\" id=\"account_settings\"");
            sb.Append("          class=\"tooltipped downwards\"");
            sb.Append("          aria-label=\"Account settings \"");
            sb.Append("          title=\"Account settings \">");
            sb.Append("          <span class=\"octicon octicon-tools\"></span>");
            sb.Append("        </a>");
            sb.Append("      </li>");
            sb.Append("      <li>");
            sb.Append("        <a class=\"tooltipped downwards\" href=\"/logout\" data-method=\"post\" id=\"logout\" title=\"Sign out\" aria-label=\"Sign out\">");
            sb.Append("          <span class=\"octicon octicon-log-out\"></span>");
            sb.Append("        </a>");
            sb.Append("      </li>");
            sb.Append("");
            sb.Append("  </ul>");
            sb.Append("");
            sb.Append("<div class=\"js-new-dropdown-contents hidden\">");
            sb.Append("  ");
            sb.Append("");
            sb.Append("<ul class=\"dropdown-menu\">");
            sb.Append("  <li>");
            sb.Append("    <a href=\"/new\"><span class=\"octicon octicon-repo-create\"></span> New repository</a>");
            sb.Append("  </li>");
            sb.Append("  <li>");
            sb.Append("    <a href=\"/organizations/new\"><span class=\"octicon octicon-organization\"></span> New organization</a>");
            sb.Append("  </li>");
            sb.Append("");
            sb.Append("");
            sb.Append("");
            sb.Append("    <li class=\"section-title\">");
            sb.Append("      <span title=\"DeanZhouLin/HtmlAgilityPackCore\">This repository</span>");
            sb.Append("    </li>");
            sb.Append("      <li>");
            sb.Append("        <a href=\"/DeanZhouLin/HtmlAgilityPackCore/issues/new\"><span class=\"octicon octicon-issue-opened\"></span> New issue</a>");
            sb.Append("      </li>");
            sb.Append("      <li>");
            sb.Append("        <a href=\"/DeanZhouLin/HtmlAgilityPackCore/settings/collaboration\"><span class=\"octicon octicon-person-add\"></span> New collaborator</a>");
            sb.Append("      </li>");
            sb.Append("</ul>");
            sb.Append("");
            sb.Append("</div>");
            sb.Append("");
            sb.Append("");
            sb.Append("    ");
            sb.Append("  </div>");
            sb.Append("</div>");
            sb.Append("");
            sb.Append("      ");
            sb.Append("");
            sb.Append("      ");
            sb.Append("");
            sb.Append("");
            sb.Append("");
            sb.Append("");
            sb.Append("          <div class=\"site\" itemscope itemtype=\"http://schema.org/WebPage\">");
            sb.Append("    ");
            sb.Append("    <div class=\"pagehead repohead instapaper_ignore readability-menu\">");
            sb.Append("      <div class=\"container\">");
            sb.Append("        ");
            sb.Append("");
            sb.Append("<ul class=\"pagehead-actions\">");
            sb.Append("");
            sb.Append("    <li class=\"subscription\">");
            sb.Append("      <form accept-charset=\"UTF-8\" action=\"/notifications/subscribe\" class=\"js-social-container\" data-autosubmit=\"true\" data-remote=\"true\" method=\"post\"><div style=\"margin:0;padding:0;display:inline\"><input name=\"authenticity_token\" type=\"hidden\" value=\"GrFK1lxGTvXROnJB5Cw0b0LKIZMzeRGBUou9uNKmMYQ=\" /></div>  <input id=\"repository_id\" name=\"repository_id\" type=\"hidden\" value=\"15697538\" />");
            sb.Append("");
            sb.Append("    <div class=\"select-menu js-menu-container js-select-menu\">");
            sb.Append("      <a class=\"social-count js-social-count\" href=\"/DeanZhouLin/HtmlAgilityPackCore/watchers\">");
            sb.Append("        1");
            sb.Append("      </a>");
            sb.Append("      <span class=\"minibutton select-menu-button with-count js-menu-target\" role=\"button\" tabindex=\"0\">");
            sb.Append("        <span class=\"js-select-button\">");
            sb.Append("          <span class=\"octicon octicon-eye-unwatch\"></span>");
            sb.Append("          Unwatch");
            sb.Append("        </span>");
            sb.Append("      </span>");
            sb.Append("");
            sb.Append("      <div class=\"select-menu-modal-holder\">");
            sb.Append("        <div class=\"select-menu-modal subscription-menu-modal js-menu-content\">");
            sb.Append("          <div class=\"select-menu-header\">");
            sb.Append("            <span class=\"select-menu-title\">Notification status</span>");
            sb.Append("            <span class=\"octicon octicon-remove-close js-menu-close\"></span>");
            sb.Append("          </div> <!-- /.select-menu-header -->");
            sb.Append("");
            sb.Append("          <div class=\"select-menu-list js-navigation-container\" role=\"menu\">");
            sb.Append("");
            sb.Append("            <div class=\"select-menu-item js-navigation-item \" role=\"menuitem\" tabindex=\"0\">");
            sb.Append("              <span class=\"select-menu-item-icon octicon octicon-check\"></span>");
            sb.Append("              <div class=\"select-menu-item-text\">");
            sb.Append("                <input id=\"do_included\" name=\"do\" type=\"radio\" value=\"included\" />");
            sb.Append("                <h4>Not watching</h4>");
            sb.Append("                <span class=\"description\">You only receive notifications for conversations in which you participate or are @mentioned.</span>");
            sb.Append("                <span class=\"js-select-button-text hidden-select-button-text\">");
            sb.Append("                  <span class=\"octicon octicon-eye-watch\"></span>");
            sb.Append("                  Watch");
            sb.Append("                </span>");
            sb.Append("              </div>");
            sb.Append("            </div> <!-- /.select-menu-item -->");
            sb.Append("");
            sb.Append("            <div class=\"select-menu-item js-navigation-item selected\" role=\"menuitem\" tabindex=\"0\">");
            sb.Append("              <span class=\"select-menu-item-icon octicon octicon octicon-check\"></span>");
            sb.Append("              <div class=\"select-menu-item-text\">");
            sb.Append("                <input checked=\"checked\" id=\"do_subscribed\" name=\"do\" type=\"radio\" value=\"subscribed\" />");
            sb.Append("                <h4>Watching</h4>");
            sb.Append("                <span class=\"description\">You receive notifications for all conversations in this repository.</span>");
            sb.Append("                <span class=\"js-select-button-text hidden-select-button-text\">");
            sb.Append("                  <span class=\"octicon octicon-eye-unwatch\"></span>");
            sb.Append("                  Unwatch");
            sb.Append("                </span>");
            sb.Append("              </div>");
            sb.Append("            </div> <!-- /.select-menu-item -->");
            sb.Append("");
            sb.Append("            <div class=\"select-menu-item js-navigation-item \" role=\"menuitem\" tabindex=\"0\">");
            sb.Append("              <span class=\"select-menu-item-icon octicon octicon-check\"></span>");
            sb.Append("              <div class=\"select-menu-item-text\">");
            sb.Append("                <input id=\"do_ignore\" name=\"do\" type=\"radio\" value=\"ignore\" />");
            sb.Append("                <h4>Ignoring</h4>");
            sb.Append("                <span class=\"description\">You do not receive any notifications for conversations in this repository.</span>");
            sb.Append("                <span class=\"js-select-button-text hidden-select-button-text\">");
            sb.Append("                  <span class=\"octicon octicon-mute\"></span>");
            sb.Append("                  Stop ignoring");
            sb.Append("                </span>");
            sb.Append("              </div>");
            sb.Append("            </div> <!-- /.select-menu-item -->");
            sb.Append("");
            sb.Append("          </div> <!-- /.select-menu-list -->");
            sb.Append("");
            sb.Append("        </div> <!-- /.select-menu-modal -->");
            sb.Append("      </div> <!-- /.select-menu-modal-holder -->");
            sb.Append("    </div> <!-- /.select-menu -->");
            sb.Append("");
            sb.Append("</form>");
            sb.Append("    </li>");
            sb.Append("");
            sb.Append("  <li>");
            sb.Append("  ");
            sb.Append("");
            sb.Append("  <div class=\"js-toggler-container js-social-container starring-container \">");
            sb.Append("    <a href=\"/DeanZhouLin/HtmlAgilityPackCore/unstar\"");
            sb.Append("      class=\"minibutton with-count js-toggler-target star-button starred upwards\"");
            sb.Append("      title=\"Unstar this repository\" data-remote=\"true\" data-method=\"post\" rel=\"nofollow\">");
            sb.Append("      <span class=\"octicon octicon-star-delete\"></span><span class=\"text\">Unstar</span>");
            sb.Append("    </a>");
            sb.Append("");
            sb.Append("    <a href=\"/DeanZhouLin/HtmlAgilityPackCore/star\"");
            sb.Append("      class=\"minibutton with-count js-toggler-target star-button unstarred upwards\"");
            sb.Append("      title=\"Star this repository\" data-remote=\"true\" data-method=\"post\" rel=\"nofollow\">");
            sb.Append("      <span class=\"octicon octicon-star\"></span><span class=\"text\">Star</span>");
            sb.Append("    </a>");
            sb.Append("");
            sb.Append("      <a class=\"social-count js-social-count\" href=\"/DeanZhouLin/HtmlAgilityPackCore/stargazers\">");
            sb.Append("        0");
            sb.Append("      </a>");
            sb.Append("  </div>");
            sb.Append("");
            sb.Append("  </li>");
            sb.Append("");
            sb.Append("");
            sb.Append("        <li>");
            sb.Append("          <a href=\"/DeanZhouLin/HtmlAgilityPackCore/fork\" class=\"minibutton with-count js-toggler-target fork-button lighter upwards\" title=\"Fork this repo\" rel=\"facebox nofollow\">");
            sb.Append("            <span class=\"octicon octicon-git-branch-create\"></span><span class=\"text\">Fork</span>");
            sb.Append("          </a>");
            sb.Append("          <a href=\"/DeanZhouLin/HtmlAgilityPackCore/network\" class=\"social-count\">0</a>");
            sb.Append("        </li>");
            sb.Append("");
            sb.Append("");
            sb.Append("</ul>");
            sb.Append("");
            sb.Append("        <h1 itemscope itemtype=\"http://data-vocabulary.org/Breadcrumb\" class=\"entry-title public\">");
            sb.Append("          <span class=\"repo-label\"><span>public</span></span>");
            sb.Append("          <span class=\"mega-octicon octicon-repo\"></span>");
            sb.Append("          <span class=\"author\">");
            sb.Append("            <a href=\"/DeanZhouLin\" class=\"url fn\" itemprop=\"url\" rel=\"author\"><span itemprop=\"title\">DeanZhouLin</span></a>");
            sb.Append("          </span>");
            sb.Append("          <span class=\"repohead-name-divider\">/</span>");
            sb.Append("          <strong><a href=\"/DeanZhouLin/HtmlAgilityPackCore\" class=\"js-current-repository js-repo-home-link\">HtmlAgilityPackCore</a></strong>");
            sb.Append("");
            sb.Append("          <span class=\"page-context-loader\">");
            sb.Append("            <img alt=\"Octocat-spinner-32\" height=\"16\" src=\"https://github.global.ssl.fastly.net/images/spinners/octocat-spinner-32.gif\" width=\"16\" />");
            sb.Append("          </span>");
            sb.Append("");
            sb.Append("        </h1>");
            sb.Append("      </div><!-- /.container -->");
            sb.Append("    </div><!-- /.repohead -->");
            sb.Append("");
            sb.Append("    <div class=\"container\">");
            sb.Append("      ");
            sb.Append("");
            sb.Append("      <div class=\"repository-with-sidebar repo-container with-full-navigation \">");
            sb.Append("");
            sb.Append("        <div class=\"repository-sidebar\">");
            sb.Append("            ");
            sb.Append("");
            sb.Append("<div class=\"sunken-menu vertical-right repo-nav js-repo-nav js-repository-container-pjax js-octicon-loaders\">");
            sb.Append("  <div class=\"sunken-menu-contents\">");
            sb.Append("    <ul class=\"sunken-menu-group\">");
            sb.Append("      <li class=\"tooltipped leftwards\" title=\"Code\">");
            sb.Append("        <a href=\"/DeanZhouLin/HtmlAgilityPackCore\" aria-label=\"Code\" class=\"selected js-selected-navigation-item sunken-menu-item\" data-gotokey=\"c\" data-pjax=\"true\" data-selected-links=\"repo_source repo_downloads repo_commits repo_tags repo_branches /DeanZhouLin/HtmlAgilityPackCore\">");
            sb.Append("          <span class=\"octicon octicon-code\"></span> <span class=\"full-word\">Code</span>");
            sb.Append("          <img alt=\"Octocat-spinner-32\" class=\"mini-loader\" height=\"16\" src=\"https://github.global.ssl.fastly.net/images/spinners/octocat-spinner-32.gif\" width=\"16\" />");
            sb.Append("</a>      </li>");
            sb.Append("");
            sb.Append("        <li class=\"tooltipped leftwards\" title=\"Issues\">");
            sb.Append("          <a href=\"/DeanZhouLin/HtmlAgilityPackCore/issues\" aria-label=\"Issues\" class=\"js-selected-navigation-item sunken-menu-item js-disable-pjax\" data-gotokey=\"i\" data-selected-links=\"repo_issues /DeanZhouLin/HtmlAgilityPackCore/issues\">");
            sb.Append("            <span class=\"octicon octicon-issue-opened\"></span> <span class=\"full-word\">Issues</span>");
            sb.Append("            <span class='counter'>0</span>");
            sb.Append("            <img alt=\"Octocat-spinner-32\" class=\"mini-loader\" height=\"16\" src=\"https://github.global.ssl.fastly.net/images/spinners/octocat-spinner-32.gif\" width=\"16\" />");
            sb.Append("</a>        </li>");
            sb.Append("");
            sb.Append("      <li class=\"tooltipped leftwards\" title=\"Pull Requests\">");
            sb.Append("        <a href=\"/DeanZhouLin/HtmlAgilityPackCore/pulls\" aria-label=\"Pull Requests\" class=\"js-selected-navigation-item sunken-menu-item js-disable-pjax\" data-gotokey=\"p\" data-selected-links=\"repo_pulls /DeanZhouLin/HtmlAgilityPackCore/pulls\">");
            sb.Append("            <span class=\"octicon octicon-git-pull-request\"></span> <span class=\"full-word\">Pull Requests</span>");
            sb.Append("            <span class='counter'>0</span>");
            sb.Append("            <img alt=\"Octocat-spinner-32\" class=\"mini-loader\" height=\"16\" src=\"https://github.global.ssl.fastly.net/images/spinners/octocat-spinner-32.gif\" width=\"16\" />");
            sb.Append("</a>      </li>");
            sb.Append("");
            sb.Append("");
            sb.Append("        <li class=\"tooltipped leftwards\" title=\"Wiki\">");
            sb.Append("          <a href=\"/DeanZhouLin/HtmlAgilityPackCore/wiki\" aria-label=\"Wiki\" class=\"js-selected-navigation-item sunken-menu-item\" data-pjax=\"true\" data-selected-links=\"repo_wiki /DeanZhouLin/HtmlAgilityPackCore/wiki\">");
            sb.Append("            <span class=\"octicon octicon-book\"></span> <span class=\"full-word\">Wiki</span>");
            sb.Append("            <img alt=\"Octocat-spinner-32\" class=\"mini-loader\" height=\"16\" src=\"https://github.global.ssl.fastly.net/images/spinners/octocat-spinner-32.gif\" width=\"16\" />");
            sb.Append("</a>        </li>");
            sb.Append("    </ul>");
            sb.Append("    <div class=\"sunken-menu-separator\"></div>");
            sb.Append("    <ul class=\"sunken-menu-group\">");
            sb.Append("");
            sb.Append("      <li class=\"tooltipped leftwards\" title=\"Pulse\">");
            sb.Append("        <a href=\"/DeanZhouLin/HtmlAgilityPackCore/pulse\" aria-label=\"Pulse\" class=\"js-selected-navigation-item sunken-menu-item\" data-pjax=\"true\" data-selected-links=\"pulse /DeanZhouLin/HtmlAgilityPackCore/pulse\">");
            sb.Append("          <span class=\"octicon octicon-pulse\"></span> <span class=\"full-word\">Pulse</span>");
            sb.Append("          <img alt=\"Octocat-spinner-32\" class=\"mini-loader\" height=\"16\" src=\"https://github.global.ssl.fastly.net/images/spinners/octocat-spinner-32.gif\" width=\"16\" />");
            sb.Append("</a>      </li>");
            sb.Append("");
            sb.Append("      <li class=\"tooltipped leftwards\" title=\"Graphs\">");
            sb.Append("        <a href=\"/DeanZhouLin/HtmlAgilityPackCore/graphs\" aria-label=\"Graphs\" class=\"js-selected-navigation-item sunken-menu-item\" data-pjax=\"true\" data-selected-links=\"repo_graphs repo_contributors /DeanZhouLin/HtmlAgilityPackCore/graphs\">");
            sb.Append("          <span class=\"octicon octicon-graph\"></span> <span class=\"full-word\">Graphs</span>");
            sb.Append("          <img alt=\"Octocat-spinner-32\" class=\"mini-loader\" height=\"16\" src=\"https://github.global.ssl.fastly.net/images/spinners/octocat-spinner-32.gif\" width=\"16\" />");
            sb.Append("</a>      </li>");
            sb.Append("");
            sb.Append("      <li class=\"tooltipped leftwards\" title=\"Network\">");
            sb.Append("        <a href=\"/DeanZhouLin/HtmlAgilityPackCore/network\" aria-label=\"Network\" class=\"js-selected-navigation-item sunken-menu-item js-disable-pjax\" data-selected-links=\"repo_network /DeanZhouLin/HtmlAgilityPackCore/network\">");
            sb.Append("          <span class=\"octicon octicon-git-branch\"></span> <span class=\"full-word\">Network</span>");
            sb.Append("          <img alt=\"Octocat-spinner-32\" class=\"mini-loader\" height=\"16\" src=\"https://github.global.ssl.fastly.net/images/spinners/octocat-spinner-32.gif\" width=\"16\" />");
            sb.Append("</a>      </li>");
            sb.Append("    </ul>");
            sb.Append("");
            sb.Append("");
            sb.Append("      <div class=\"sunken-menu-separator\"></div>");
            sb.Append("      <ul class=\"sunken-menu-group\">");
            sb.Append("        <li class=\"tooltipped leftwards\" title=\"Settings\">");
            sb.Append("          <a href=\"/DeanZhouLin/HtmlAgilityPackCore/settings\"");
            sb.Append("            class=\"sunken-menu-item\" data-pjax aria-label=\"Settings\">");
            sb.Append("            <span class=\"octicon octicon-tools\"></span> <span class=\"full-word\">Settings</span>");
            sb.Append("            <img alt=\"Octocat-spinner-32\" class=\"mini-loader\" height=\"16\" src=\"https://github.global.ssl.fastly.net/images/spinners/octocat-spinner-32.gif\" width=\"16\" />");
            sb.Append("          </a>");
            sb.Append("        </li>");
            sb.Append("      </ul>");
            sb.Append("  </div>");
            sb.Append("</div>");
            sb.Append("");
            sb.Append("            <div class=\"only-with-full-nav\">");
            sb.Append("              ");
            sb.Append("");
            sb.Append("  ");
            sb.Append("");
            sb.Append("<div class=\"clone-url open\"");
            sb.Append("  data-protocol-type=\"http\"");
            sb.Append("  data-url=\"/users/set_protocol?protocol_selector=http&amp;protocol_type=push\">");
            sb.Append("  <h3><strong>HTTPS</strong> clone URL</h3>");
            sb.Append("  <div class=\"clone-url-box\">");
            sb.Append("    <input type=\"text\" class=\"clone js-url-field\"");
            sb.Append("           value=\"https://github.com/DeanZhouLin/HtmlAgilityPackCore.git\" readonly=\"readonly\">");
            sb.Append("");
            sb.Append("    <span class=\"js-zeroclipboard url-box-clippy minibutton zeroclipboard-button\" data-clipboard-text=\"https://github.com/DeanZhouLin/HtmlAgilityPackCore.git\" data-copied-hint=\"copied!\" title=\"copy to clipboard\"><span class=\"octicon octicon-clippy\"></span></span>");
            sb.Append("  </div>");
            sb.Append("</div>");
            sb.Append("");
            sb.Append("  ");
            sb.Append("");
            sb.Append("<div class=\"clone-url \"");
            sb.Append("  data-protocol-type=\"ssh\"");
            sb.Append("  data-url=\"/users/set_protocol?protocol_selector=ssh&amp;protocol_type=push\">");
            sb.Append("  <h3><strong>SSH</strong> clone URL</h3>");
            sb.Append("  <div class=\"clone-url-box\">");
            sb.Append("    <input type=\"text\" class=\"clone js-url-field\"");
            sb.Append("           value=\"git@github.com:DeanZhouLin/HtmlAgilityPackCore.git\" readonly=\"readonly\">");
            sb.Append("");
            sb.Append("    <span class=\"js-zeroclipboard url-box-clippy minibutton zeroclipboard-button\" data-clipboard-text=\"git@github.com:DeanZhouLin/HtmlAgilityPackCore.git\" data-copied-hint=\"copied!\" title=\"copy to clipboard\"><span class=\"octicon octicon-clippy\"></span></span>");
            sb.Append("  </div>");
            sb.Append("</div>");
            sb.Append("");
            sb.Append("  ");
            sb.Append("");
            sb.Append("<div class=\"clone-url \"");
            sb.Append("  data-protocol-type=\"subversion\"");
            sb.Append("  data-url=\"/users/set_protocol?protocol_selector=subversion&amp;protocol_type=push\">");
            sb.Append("  <h3><strong>Subversion</strong> checkout URL</h3>");
            sb.Append("  <div class=\"clone-url-box\">");
            sb.Append("    <input type=\"text\" class=\"clone js-url-field\"");
            sb.Append("           value=\"https://github.com/DeanZhouLin/HtmlAgilityPackCore\" readonly=\"readonly\">");
            sb.Append("");
            sb.Append("    <span class=\"js-zeroclipboard url-box-clippy minibutton zeroclipboard-button\" data-clipboard-text=\"https://github.com/DeanZhouLin/HtmlAgilityPackCore\" data-copied-hint=\"copied!\" title=\"copy to clipboard\"><span class=\"octicon octicon-clippy\"></span></span>");
            sb.Append("  </div>");
            sb.Append("</div>");
            sb.Append("");
            sb.Append("");
            sb.Append("<p class=\"clone-options\">You can clone with");
            sb.Append("      <a href=\"#\" class=\"js-clone-selector\" data-protocol=\"http\">HTTPS</a>,");
            sb.Append("      <a href=\"#\" class=\"js-clone-selector\" data-protocol=\"ssh\">SSH</a>,");
            sb.Append("      or <a href=\"#\" class=\"js-clone-selector\" data-protocol=\"subversion\">Subversion</a>.");
            sb.Append("  <span class=\"octicon help tooltipped upwards\" title=\"Get help on which URL is right for you.\">");
            sb.Append("    <a href=\"https://help.github.com/articles/which-remote-url-should-i-use\">");
            sb.Append("    <span class=\"octicon octicon-question\"></span>");
            sb.Append("    </a>");
            sb.Append("  </span>");
            sb.Append("</p>");
            sb.Append("");
            sb.Append("");
            sb.Append("  <a href=\"github-windows://openRepo/https://github.com/DeanZhouLin/HtmlAgilityPackCore\" class=\"minibutton sidebar-button\">");
            sb.Append("    <span class=\"octicon octicon-device-desktop\"></span>");
            sb.Append("    Clone in Desktop");
            sb.Append("  </a>");
            sb.Append("");
            sb.Append("              <a href=\"/DeanZhouLin/HtmlAgilityPackCore/archive/master.zip\"");
            sb.Append("                 class=\"minibutton sidebar-button\"");
            sb.Append("                 title=\"Download this repository as a zip file\"");
            sb.Append("                 rel=\"nofollow\">");
            sb.Append("                <span class=\"octicon octicon-cloud-download\"></span>");
            sb.Append("                Download ZIP");
            sb.Append("              </a>");
            sb.Append("            </div>");
            sb.Append("        </div><!-- /.repository-sidebar -->");
            sb.Append("");
            sb.Append("        <div id=\"js-repo-pjax-container\" class=\"repository-content context-loader-container\" data-pjax-container>");
            sb.Append("          ");
            sb.Append("");
            sb.Append("<span id=\"js-show-full-navigation\"></span>");
            sb.Append("");
            sb.Append("<div class=\"repository-meta js-details-container  js-dark-ship-traffic-graphs\" data-url=\"/DeanZhouLin/HtmlAgilityPackCore/graphs/ping\" data-data-url=\"/DeanZhouLin/HtmlAgilityPackCore/graphs/ping-data\">");
            sb.Append("    <div class=\"repository-description js-details-show\">");
            sb.Append("      <p>HtmlAgilityPack的使用 封装基类</p>");
            sb.Append("    </div>");
            sb.Append("");
            sb.Append("");
            sb.Append("    <span class=\"edit-link js-details-show js-details-target\">— <a href=\"#\">Edit</a></span>");
            sb.Append("    <form accept-charset=\"UTF-8\" action=\"/DeanZhouLin/HtmlAgilityPackCore/settings/update_meta\" class=\"edit-repository-meta js-details-edit\" method=\"post\"><div style=\"margin:0;padding:0;display:inline\"><input name=\"_method\" type=\"hidden\" value=\"put\" /><input name=\"authenticity_token\" type=\"hidden\" value=\"GrFK1lxGTvXROnJB5Cw0b0LKIZMzeRGBUou9uNKmMYQ=\" /></div>");
            sb.Append("");
            sb.Append("      <div class=\"field description-field\">");
            sb.Append("        <label for=\"repo_description\">Description</label>");
            sb.Append("        <input type=\"text\" name=\"repo_description\" value=\"HtmlAgilityPack的使用 封装基类\" placeholder=\"Short description of this repository\" />");
            sb.Append("      </div>");
            sb.Append("");
            sb.Append("      <div class=\"field website-field\" >");
            sb.Append("        <label for=\"repo_homepage\">Website</label>");
            sb.Append("        <input type=\"text\" name=\"repo_homepage\" value=\"\" placeholder=\"Website for this repository (optional)\" />");
            sb.Append("      </div>");
            sb.Append("");
            sb.Append("      <button class=\"button classy\">Save</button>");
            sb.Append("      <span class=\"cancel\">or <a href=\"#\" class=\"js-details-target\">cancel</a></span>");
            sb.Append("</form>");
            sb.Append("</div>");
            sb.Append("");
            sb.Append("<div class=\"capped-box overall-summary \">");
            sb.Append("");
            sb.Append("  <div class=\"stats-switcher-viewport js-stats-switcher-viewport\">");
            sb.Append("");
            sb.Append("    <ul class=\"numbers-summary\">");
            sb.Append("      <li class=\"commits\">");
            sb.Append("        <a data-pjax href=\"/DeanZhouLin/HtmlAgilityPackCore/commits/master\">");
            sb.Append("            <span class=\"num\">");
            sb.Append("              <span class=\"octicon octicon-history\"></span>");
            sb.Append("              2");
            sb.Append("            </span>");
            sb.Append("            commits");
            sb.Append("        </a>");
            sb.Append("      </li>");
            sb.Append("      <li>");
            sb.Append("        <a data-pjax href=\"/DeanZhouLin/HtmlAgilityPackCore/branches\">");
            sb.Append("          <span class=\"num\">");
            sb.Append("            <span class=\"octicon octicon-git-branch\"></span>");
            sb.Append("            1");
            sb.Append("          </span>");
            sb.Append("          branch");
            sb.Append("        </a>");
            sb.Append("      </li>");
            sb.Append("");
            sb.Append("      <li>");
            sb.Append("        <a data-pjax href=\"/DeanZhouLin/HtmlAgilityPackCore/releases\">");
            sb.Append("          <span class=\"num\">");
            sb.Append("            <span class=\"octicon octicon-tag\"></span>");
            sb.Append("            0");
            sb.Append("          </span>");
            sb.Append("          releases");
            sb.Append("        </a>");
            sb.Append("      </li>");
            sb.Append("");
            sb.Append("      <li>");
            sb.Append("          <a href=\"/DeanZhouLin/HtmlAgilityPackCore/graphs/contributors\" class=\"js-deferred-content\" data-url=\"/DeanZhouLin/HtmlAgilityPackCore/contributors_size\">");
            sb.Append("            <span class=\"num\">");
            sb.Append("              <span class=\"octicon octicon-organization\"></span>");
            sb.Append("            </span>");
            sb.Append("            Fetching contributors");
            sb.Append("          </a>");
            sb.Append("      </li>");
            sb.Append("    </ul>");
            sb.Append("");
            sb.Append("      <div class=\"repository-lang-stats\">");
            sb.Append("        <ol class=\"repository-lang-stats-numbers\">");
            sb.Append("          <li>");
            sb.Append("              <a href=\"/DeanZhouLin/HtmlAgilityPackCore/search?l=c%23\">");
            sb.Append("                <span class=\"color-block language-color\" style=\"background-color:#5a25a2;\"></span>");
            sb.Append("                <span class=\"lang\">C#</span>");
            sb.Append("                <span class=\"percent\">100%</span>");
            sb.Append("              </a>");
            sb.Append("          </li>");
            sb.Append("        </ol>");
            sb.Append("      </div>");
            sb.Append("  </div>");
            sb.Append("");
            sb.Append("</div>");
            sb.Append("");
            sb.Append("  <a href=\"#\"");
            sb.Append("     class=\"repository-lang-stats-graph js-toggle-lang-stats tooltipped downwards\"");
            sb.Append("     title=\"Show language statistics\"");
            sb.Append("     style=\"background-color:#5a25a2\">");
            sb.Append("  <span class=\"language-color\" style=\"width:100%; background-color:#5a25a2;\" itemprop=\"keywords\">C#</span>");
            sb.Append("  </a>");
            sb.Append("");
            sb.Append("");
            sb.Append("  <div");
            sb.Append("    >");
            sb.Append("  </div>");
            sb.Append("");
            sb.Append("");
            sb.Append("<div class=\"file-navigation in-mid-page\">");
            sb.Append("    <a href=\"/DeanZhouLin/HtmlAgilityPackCore/compare\" aria-label=\"Compare, review, create a pull request\" class=\"minibutton compact primary tooltipped downwards\" title=\"Compare &amp; review\" data-pjax>");
            sb.Append("      <span class=\"octicon octicon-git-compare\"></span>");
            sb.Append("    </a>");
            sb.Append("");
            sb.Append("  ");
            sb.Append("");
            sb.Append("<div class=\"select-menu js-menu-container js-select-menu\" >");
            sb.Append("  <span class=\"minibutton select-menu-button js-menu-target\" data-hotkey=\"w\"");
            sb.Append("    data-master-branch=\"master\"");
            sb.Append("    data-ref=\"master\"");
            sb.Append("    role=\"button\" aria-label=\"Switch branches or tags\" tabindex=\"0\">");
            sb.Append("    <span class=\"octicon octicon-git-branch\"></span>");
            sb.Append("    <i>branch:</i>");
            sb.Append("    <span class=\"js-select-button\">master</span>");
            sb.Append("  </span>");
            sb.Append("");
            sb.Append("  <div class=\"select-menu-modal-holder js-menu-content js-navigation-container\" data-pjax>");
            sb.Append("");
            sb.Append("    <div class=\"select-menu-modal\">");
            sb.Append("      <div class=\"select-menu-header\">");
            sb.Append("        <span class=\"select-menu-title\">Switch branches/tags</span>");
            sb.Append("        <span class=\"octicon octicon-remove-close js-menu-close\"></span>");
            sb.Append("      </div> <!-- /.select-menu-header -->");
            sb.Append("");
            sb.Append("      <div class=\"select-menu-filters\">");
            sb.Append("        <div class=\"select-menu-text-filter\">");
            sb.Append("          <input type=\"text\" aria-label=\"Find or create a branch…\" id=\"context-commitish-filter-field\" class=\"js-filterable-field js-navigation-enable\" placeholder=\"Find or create a branch…\">");
            sb.Append("        </div>");
            sb.Append("        <div class=\"select-menu-tabs\">");
            sb.Append("          <ul>");
            sb.Append("            <li class=\"select-menu-tab\">");
            sb.Append("              <a href=\"#\" data-tab-filter=\"branches\" class=\"js-select-menu-tab\">Branches</a>");
            sb.Append("            </li>");
            sb.Append("            <li class=\"select-menu-tab\">");
            sb.Append("              <a href=\"#\" data-tab-filter=\"tags\" class=\"js-select-menu-tab\">Tags</a>");
            sb.Append("            </li>");
            sb.Append("          </ul>");
            sb.Append("        </div><!-- /.select-menu-tabs -->");
            sb.Append("      </div><!-- /.select-menu-filters -->");
            sb.Append("");
            sb.Append("      <div class=\"select-menu-list select-menu-tab-bucket js-select-menu-tab-bucket\" data-tab-filter=\"branches\">");
            sb.Append("");
            sb.Append("        <div data-filterable-for=\"context-commitish-filter-field\" data-filterable-type=\"substring\">");
            sb.Append("");
            sb.Append("");
            sb.Append("            <div class=\"select-menu-item js-navigation-item selected\">");
            sb.Append("              <span class=\"select-menu-item-icon octicon octicon-check\"></span>");
            sb.Append("              <a href=\"/DeanZhouLin/HtmlAgilityPackCore/tree/master\"");
            sb.Append("                 data-name=\"master\"");
            sb.Append("                 data-skip-pjax=\"true\"");
            sb.Append("                 rel=\"nofollow\"");
            sb.Append("                 class=\"js-navigation-open select-menu-item-text js-select-button-text css-truncate-target\"");
            sb.Append("                 title=\"master\">master</a>");
            sb.Append("            </div> <!-- /.select-menu-item -->");
            sb.Append("        </div>");
            sb.Append("");
            sb.Append("          <form accept-charset=\"UTF-8\" action=\"/DeanZhouLin/HtmlAgilityPackCore/branches\" class=\"js-create-branch select-menu-item select-menu-new-item-form js-navigation-item js-new-item-form\" method=\"post\"><div style=\"margin:0;padding:0;display:inline\"><input name=\"authenticity_token\" type=\"hidden\" value=\"GrFK1lxGTvXROnJB5Cw0b0LKIZMzeRGBUou9uNKmMYQ=\" /></div>");
            sb.Append("            <span class=\"octicon octicon-git-branch-create select-menu-item-icon\"></span>");
            sb.Append("            <div class=\"select-menu-item-text\">");
            sb.Append("              <h4>Create branch: <span class=\"js-new-item-name\"></span></h4>");
            sb.Append("              <span class=\"description\">from ‘master’</span>");
            sb.Append("            </div>");
            sb.Append("            <input type=\"hidden\" name=\"name\" id=\"name\" class=\"js-new-item-value\">");
            sb.Append("            <input type=\"hidden\" name=\"branch\" id=\"branch\" value=\"master\" />");
            sb.Append("            <input type=\"hidden\" name=\"path\" id=\"path\" value=\"\" />");
            sb.Append("          </form> <!-- /.select-menu-item -->");
            sb.Append("");
            sb.Append("      </div> <!-- /.select-menu-list -->");
            sb.Append("");
            sb.Append("      <div class=\"select-menu-list select-menu-tab-bucket js-select-menu-tab-bucket\" data-tab-filter=\"tags\">");
            sb.Append("        <div data-filterable-for=\"context-commitish-filter-field\" data-filterable-type=\"substring\">");
            sb.Append("");
            sb.Append("");
            sb.Append("        </div>");
            sb.Append("");
            sb.Append("        <div class=\"select-menu-no-results\">Nothing to show</div>");
            sb.Append("      </div> <!-- /.select-menu-list -->");
            sb.Append("");
            sb.Append("    </div> <!-- /.select-menu-modal -->");
            sb.Append("  </div> <!-- /.select-menu-modal-holder -->");
            sb.Append("</div> <!-- /.select-menu -->");
            sb.Append("");
            sb.Append("");
            sb.Append("  <div class=\"breadcrumb\"><span class='repo-root js-repo-root'><span itemscope=\"\" itemtype=\"http://data-vocabulary.org/Breadcrumb\"><a href=\"/DeanZhouLin/HtmlAgilityPackCore\" data-branch=\"master\" data-direction=\"back\" data-pjax=\"true\" itemscope=\"url\"><span itemprop=\"title\">HtmlAgilityPackCore</span></a></span></span><span class=\"separator\"> / </span><form action=\"/DeanZhouLin/HtmlAgilityPackCore/new/master\" class=\"js-new-blob-form tooltipped rightwards new-file-link\" method=\"post\" title=\"Create a new file here\"><span aria-label=\"Create a new file here\" class=\"js-new-blob-submit octicon octicon-file-add\" data-test-id=\"create-new-git-file\" role=\"button\"></span></form></div>");
            sb.Append("</div>");
            sb.Append("");
            sb.Append("");
            sb.Append("");
            sb.Append("<a href=\"/DeanZhouLin/HtmlAgilityPackCore/find/master\"");
            sb.Append("  data-hotkey=\"t\" class=\"js-show-file-finder\" style=\"display:none\" data-pjax>Show File Finder</a>");
            sb.Append("<div class=\"bubble files-bubble\">");
            sb.Append("");
            sb.Append("    <div class=\"commit commit-loader commit-tease js-details-container js-deferred-content\" data-url=\"/DeanZhouLin/HtmlAgilityPackCore/tree-commit/master\">");
            sb.Append("      <p class=\"commit-title blank\">");
            sb.Append("        Fetching latest commit…");
            sb.Append("      </p>");
            sb.Append("      <div class=\"commit-meta\">");
            sb.Append("        <p class=\"loader-loading\"><img alt=\"Octocat-spinner-32-eaf2f5\" height=\"16\" src=\"https://github.global.ssl.fastly.net/images/spinners/octocat-spinner-32-EAF2F5.gif\" width=\"16\" /></p>");
            sb.Append("        <p class=\"loader-error\">Cannot retrieve the latest commit at this time</p>");
            sb.Append("      </div>");
            sb.Append("    </div>");
            sb.Append("");
            sb.Append("  <table class=\"files\" data-pjax>");
            sb.Append("");
            sb.Append("    ");
            sb.Append("<tbody class=\"\"");
            sb.Append("  data-url=\"/DeanZhouLin/HtmlAgilityPackCore/file-list/master\">");
            sb.Append("    <tr>");
            sb.Append("      <td class=\"icon\">");
            sb.Append("        <span class=\"octicon octicon-file-directory\"></span>");
            sb.Append("        <img alt=\"Octocat-spinner-32\" class=\"spinner\" height=\"16\" src=\"https://github.global.ssl.fastly.net/images/spinners/octocat-spinner-32.gif\" width=\"16\" />");
            sb.Append("      </td>");
            sb.Append("      <td class=\"content\">");
            sb.Append("        <span class=\"css-truncate css-truncate-target\"><a href=\"/DeanZhouLin/HtmlAgilityPackCore/tree/master/HtmlAgilityPackConsoleTest\" class=\"js-directory-link\" id=\"24478478959d2099c33cca7b5cee475e-e68fd170591b6679752e84ac1bccf04de5cafcce\" title=\"HtmlAgilityPackConsoleTest\">HtmlAgilityPackConsoleTest</a></span>");
            sb.Append("      </td>");
            sb.Append("      <td class=\"message\">");
            sb.Append("        <span class=\"css-truncate css-truncate-target\"><a href=\"/DeanZhouLin/HtmlAgilityPackCore/commit/4e360f9c625eff3f0f45d88f10c8cbd30d02dc6b\" class=\"message\" data-pjax=\"true\" title=\"Add Solution\">Add Solution</a></span>");
            sb.Append("      </td>");
            sb.Append("      <td class=\"age\"><span class=\"css-truncate css-truncate-target\"><time class=\"js-relative-date\" datetime=\"2014-01-06T23:05:49-08:00\" title=\"2014-01-06 23:05:49\">January 06, 2014</time></span></td>");
            sb.Append("    </tr>");
            sb.Append("    <tr>");
            sb.Append("      <td class=\"icon\">");
            sb.Append("        <span class=\"octicon octicon-file-directory\"></span>");
            sb.Append("        <img alt=\"Octocat-spinner-32\" class=\"spinner\" height=\"16\" src=\"https://github.global.ssl.fastly.net/images/spinners/octocat-spinner-32.gif\" width=\"16\" />");
            sb.Append("      </td>");
            sb.Append("      <td class=\"content\">");
            sb.Append("        <span class=\"css-truncate css-truncate-target\"><a href=\"/DeanZhouLin/HtmlAgilityPackCore/tree/master/HtmlAgilityPackHelperLib\" class=\"js-directory-link\" id=\"d6bea72375ad837e2e9f5883033c502f-7cf3363ff9fa67ddade025fd522cbbfdd5b49e08\" title=\"HtmlAgilityPackHelperLib\">HtmlAgilityPackHelperLib</a></span>");
            sb.Append("      </td>");
            sb.Append("      <td class=\"message\">");
            sb.Append("        <span class=\"css-truncate css-truncate-target\"><a href=\"/DeanZhouLin/HtmlAgilityPackCore/commit/4e360f9c625eff3f0f45d88f10c8cbd30d02dc6b\" class=\"message\" data-pjax=\"true\" title=\"Add Solution\">Add Solution</a></span>");
            sb.Append("      </td>");
            sb.Append("      <td class=\"age\"><span class=\"css-truncate css-truncate-target\"><time class=\"js-relative-date\" datetime=\"2014-01-06T23:05:49-08:00\" title=\"2014-01-06 23:05:49\">January 06, 2014</time></span></td>");
            sb.Append("    </tr>");
            sb.Append("    <tr>");
            sb.Append("      <td class=\"icon\">");
            sb.Append("        <span class=\"octicon octicon-file-text\"></span>");
            sb.Append("        <img alt=\"Octocat-spinner-32\" class=\"spinner\" height=\"16\" src=\"https://github.global.ssl.fastly.net/images/spinners/octocat-spinner-32.gif\" width=\"16\" />");
            sb.Append("      </td>");
            sb.Append("      <td class=\"content\">");
            sb.Append("        <span class=\"css-truncate css-truncate-target\"><a href=\"/DeanZhouLin/HtmlAgilityPackCore/blob/master/.gitattributes\" class=\"js-directory-link\" id=\"fc723d30b02a4cca7a534518111c1a66-1ff0c423042b46cb1d617b81efb715defbe8054d\" title=\".gitattributes\">.gitattributes</a></span>");
            sb.Append("      </td>");
            sb.Append("      <td class=\"message\">");
            sb.Append("        <span class=\"css-truncate css-truncate-target\"><a href=\"/DeanZhouLin/HtmlAgilityPackCore/commit/be91facf1edda9bb4d030eb740922925056c45a0\" class=\"message\" data-pjax=\"true\" title=\"Initial commit to add default .gitIgnore and .gitAttribute files.\">Initial commit to add default .gitIgnore and .gitAttribute files.</a></span>");
            sb.Append("      </td>");
            sb.Append("      <td class=\"age\"><span class=\"css-truncate css-truncate-target\"><time class=\"js-relative-date\" datetime=\"2014-01-06T23:05:35-08:00\" title=\"2014-01-06 23:05:35\">January 06, 2014</time></span></td>");
            sb.Append("    </tr>");
            sb.Append("    <tr>");
            sb.Append("      <td class=\"icon\">");
            sb.Append("        <span class=\"octicon octicon-file-text\"></span>");
            sb.Append("        <img alt=\"Octocat-spinner-32\" class=\"spinner\" height=\"16\" src=\"https://github.global.ssl.fastly.net/images/spinners/octocat-spinner-32.gif\" width=\"16\" />");
            sb.Append("      </td>");
            sb.Append("      <td class=\"content\">");
            sb.Append("        <span class=\"css-truncate css-truncate-target\"><a href=\"/DeanZhouLin/HtmlAgilityPackCore/blob/master/.gitignore\" class=\"js-directory-link\" id=\"a084b794bc0759e7a6b77810e01874f2-1bc915c5cb7185a9438de28a7b1a7dfe8c01ee7f\" title=\".gitignore\">.gitignore</a></span>");
            sb.Append("      </td>");
            sb.Append("      <td class=\"message\">");
            sb.Append("        <span class=\"css-truncate css-truncate-target\"><a href=\"/DeanZhouLin/HtmlAgilityPackCore/commit/be91facf1edda9bb4d030eb740922925056c45a0\" class=\"message\" data-pjax=\"true\" title=\"Initial commit to add default .gitIgnore and .gitAttribute files.\">Initial commit to add default .gitIgnore and .gitAttribute files.</a></span>");
            sb.Append("      </td>");
            sb.Append("      <td class=\"age\"><span class=\"css-truncate css-truncate-target\"><time class=\"js-relative-date\" datetime=\"2014-01-06T23:05:35-08:00\" title=\"2014-01-06 23:05:35\">January 06, 2014</time></span></td>");
            sb.Append("    </tr>");
            sb.Append("    <tr>");
            sb.Append("      <td class=\"icon\">");
            sb.Append("        <span class=\"octicon octicon-file-text\"></span>");
            sb.Append("        <img alt=\"Octocat-spinner-32\" class=\"spinner\" height=\"16\" src=\"https://github.global.ssl.fastly.net/images/spinners/octocat-spinner-32.gif\" width=\"16\" />");
            sb.Append("      </td>");
            sb.Append("      <td class=\"content\">");
            sb.Append("        <span class=\"css-truncate css-truncate-target\"><a href=\"/DeanZhouLin/HtmlAgilityPackCore/blob/master/HtmlAgilityPackCore.sln\" class=\"js-directory-link\" id=\"84b84ed45d2fc17891840cf8a24fd780-d2793daad84ae111dad6364a187183e072d9e597\" title=\"HtmlAgilityPackCore.sln\">HtmlAgilityPackCore.sln</a></span>");
            sb.Append("      </td>");
            sb.Append("      <td class=\"message\">");
            sb.Append("        <span class=\"css-truncate css-truncate-target\"><a href=\"/DeanZhouLin/HtmlAgilityPackCore/commit/4e360f9c625eff3f0f45d88f10c8cbd30d02dc6b\" class=\"message\" data-pjax=\"true\" title=\"Add Solution\">Add Solution</a></span>");
            sb.Append("      </td>");
            sb.Append("      <td class=\"age\"><span class=\"css-truncate css-truncate-target\"><time class=\"js-relative-date\" datetime=\"2014-01-06T23:05:49-08:00\" title=\"2014-01-06 23:05:49\">January 06, 2014</time></span></td>");
            sb.Append("    </tr>");
            sb.Append("</tbody>");
            sb.Append("");
            sb.Append("  </table>");
            sb.Append("</div>");
            sb.Append("");
            sb.Append("  ");
            sb.Append("");
            sb.Append("  <div class=\"flash-messages\">");
            sb.Append("    <div class=\"flash\">");
            sb.Append("      <a href=\"/DeanZhouLin/HtmlAgilityPackCore/new/master?readme=1\" class=\"minibutton blue flash-action\">");
            sb.Append("        <span class=\"octicon octicon-book\"></span>");
            sb.Append("        Add a README");
            sb.Append("      </a>");
            sb.Append("      We recommend <a href=\"/DeanZhouLin/HtmlAgilityPackCore/new/master?readme=1\">adding a README</a>");
            sb.Append("      to this repository to help give people an overview of your project.");
            sb.Append("    </div>");
            sb.Append("  </div>");
            sb.Append("");
            sb.Append("");
            sb.Append("");
            sb.Append("");
            sb.Append("        </div>");
            sb.Append("");
            sb.Append("      </div><!-- /.repo-container -->");
            sb.Append("      <div class=\"modal-backdrop\"></div>");
            sb.Append("    </div><!-- /.container -->");
            sb.Append("  </div><!-- /.site -->");
            sb.Append("");
            sb.Append("");
            sb.Append("    </div><!-- /.wrapper -->");
            sb.Append("");
            sb.Append("      <div class=\"container\">");
            sb.Append("  <div class=\"site-footer\">");
            sb.Append("    <ul class=\"site-footer-links right\">");
            sb.Append("      <li><a href=\"https://status.github.com/\">Status</a></li>");
            sb.Append("      <li><a href=\"http://developer.github.com\">API</a></li>");
            sb.Append("      <li><a href=\"http://training.github.com\">Training</a></li>");
            sb.Append("      <li><a href=\"http://shop.github.com\">Shop</a></li>");
            sb.Append("      <li><a href=\"/blog\">Blog</a></li>");
            sb.Append("      <li><a href=\"/about\">About</a></li>");
            sb.Append("");
            sb.Append("    </ul>");
            sb.Append("");
            sb.Append("    <a href=\"/\">");
            sb.Append("      <span class=\"mega-octicon octicon-mark-github\"></span>");
            sb.Append("    </a>");
            sb.Append("");
            sb.Append("    <ul class=\"site-footer-links\">");
            sb.Append("      <li>&copy; 2014 <span title=\"0.03871s from github-fe136-cp1-prd.iad.github.net\">GitHub</span>, Inc.</li>");
            sb.Append("        <li><a href=\"/site/terms\">Terms</a></li>");
            sb.Append("        <li><a href=\"/site/privacy\">Privacy</a></li>");
            sb.Append("        <li><a href=\"/security\">Security</a></li>");
            sb.Append("        <li><a href=\"/contact\">Contact</a></li>");
            sb.Append("    </ul>");
            sb.Append("  </div><!-- /.site-footer -->");
            sb.Append("</div><!-- /.container -->");
            sb.Append("");
            sb.Append("");
            sb.Append("    <div class=\"fullscreen-overlay js-fullscreen-overlay\" id=\"fullscreen_overlay\">");
            sb.Append("  <div class=\"fullscreen-container js-fullscreen-container\">");
            sb.Append("    <div class=\"textarea-wrap\">");
            sb.Append("      <textarea name=\"fullscreen-contents\" id=\"fullscreen-contents\" class=\"js-fullscreen-contents\" placeholder=\"\" data-suggester=\"fullscreen_suggester\"></textarea>");
            sb.Append("          <div class=\"suggester-container\">");
            sb.Append("              <div class=\"suggester fullscreen-suggester js-navigation-container\" id=\"fullscreen_suggester\"");
            sb.Append("                 data-url=\"/DeanZhouLin/HtmlAgilityPackCore/suggestions/commit\">");
            sb.Append("              </div>");
            sb.Append("          </div>");
            sb.Append("    </div>");
            sb.Append("  </div>");
            sb.Append("  <div class=\"fullscreen-sidebar\">");
            sb.Append("    <a href=\"#\" class=\"exit-fullscreen js-exit-fullscreen tooltipped leftwards\" title=\"Exit Zen Mode\">");
            sb.Append("      <span class=\"mega-octicon octicon-screen-normal\"></span>");
            sb.Append("    </a>");
            sb.Append("    <a href=\"#\" class=\"theme-switcher js-theme-switcher tooltipped leftwards\"");
            sb.Append("      title=\"Switch themes\">");
            sb.Append("      <span class=\"octicon octicon-color-mode\"></span>");
            sb.Append("    </a>");
            sb.Append("  </div>");
            sb.Append("</div>");
            sb.Append("");
            sb.Append("");
            sb.Append("");
            sb.Append("    <div id=\"ajax-error-message\" class=\"flash flash-error\">");
            sb.Append("      <span class=\"octicon octicon-alert\"></span>");
            sb.Append("      <a href=\"#\" class=\"octicon octicon-remove-close close ajax-error-dismiss\"></a>");
            sb.Append("      Something went wrong with that request. Please try again.");
            sb.Append("    </div>");
            sb.Append("");
            sb.Append("  </body>");
            sb.Append("</html>");
            #endregion
            var htmlDocument = HtmlAgilityPackHelper.CreateHtmlDocument();
            var html = "<a src=\"http://www.1juhao.com/descpics/images/1102880001/1.jpg\"></a><iframe src=\"http://www.1juhao.com/descpics/images/1102940001/2.jpg\"><p rowspan=\"3\" colspan=\"2\" >Your browser does not support iframes.</p></iframe>";
            html = sb.ToString();
            htmlDocument.LoadHtml(html);

            var res = htmlDocument.GetEntireNodes();

            var nodes = htmlDocument.DocumentNode.SelectNodes("*");
            foreach (var node in nodes)
            {
                foreach (var attr in node.Attributes)
                {
                    
                    //Console.WriteLine(node.Name + "|" + attr.Name + "|" + attr.Value);
                }

                if (node.Attributes != null && node.Attributes.Count>0)
                {
                    //node.Attributes.Add(node.Attributes[0].Name + "1", node.Attributes[0].Value);

                }

            }

            Console.WriteLine(nodes.Count);
            Console.WriteLine(htmlDocument.ParseString());
            Console.ReadLine();
        }
    }
}
